### PR TITLE
Revert back to browserHistory

### LINKED ISSUE #71: Links to Job Postings Broken
When you click on a link to view a job posting on an external site, the app takes you back to the main page instead of to the external link. The link is captured in the address bar, but a link to our application precedes it, and causes our root page to render.

The ability to visit external links was working previously. However, when we changed the router in [PR 70](https://github.com/LookingForMe/lookingForFrontEnd/pull/70) it appears we broke it.

May need to determine how to use external links when using hashHistory, or potentially revisit alternatives to hashHistory to respond to [issue 63](https://github.com/LookingForMe/lookingForFrontEnd/issues/63). Research on that issue may provide alternatives, particularly [this link](https://www.themarketingtechnologist.co/react-router-an-introduction/).

### PR DESCRIPTION
**Pull request by saylerb**
Fixes #71 

Reverting back to using browserHistory instead of hashHistory.

I was banging my head against the wall today trying to get this to work, and I finally came around to playing with the express server.  It seems like changing the route from `"/"` to `"*"` fixed everything.

I also tried to convert some of the server code to ES6 in anticipation of Lucy's style guide, but I couldn't use `export default app` at the bottom instead of `module.exports = app`. Not sure why.

I tested this using `nodemon` as well as using `web-pack-server`. It seems to correctly support opening a new tab to view the detail page, as well as correctly opens a new tab when clicking "View job posting" on the detail page. 

 I haven't wrote any automated tests for this, since I'm still pretty new to routing in react. Suggestions for how to test this are welcome!

To 'test' this branch:

1. Pull Down the branch
1. Check running on nodemon server (`npm start`)
   * Navigate to `localhost:8080/`
   * click "view details" on one of the jobs OR try to open "view details" in a new tab.
   * Does the detail page load correctly? If yes, view job posting.
   * Does a new tab open with the external job posting?

1. Check running on webpack-dev server (`npm run dev`)
  * Navigate to `http://localhost:8080/webpack-dev-server/` 
  * click "view details" on one of the jobs OR try to open "view details" in a new tab.
  * Does the detail page load correctly? If yes, click "view job posting".
  * Does a new tab open with the external job posting?

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -1,17 +1,16 @@
...
 app.use(express.static(path.join(__dirname, 'public')));
 
-app.get('/', function(request, response) {
-  response.sendFile(__dirname + '/public/index.html');
+app.get('*', function(request, response) {
+  response.sendFile(path.resolve(__dirname, 'public', 'index.html'))
 });
 
-app.listen(PORT, function() {
-  console.log("Server is up and running on port: " + PORT)
```
Comment (lucyfox4131) [inline server.js]: Why is this better lower case?

File: server.js [hunk 2]
```diff
@@ -1,17 +1,16 @@
...
+const express = require('express');
+const port = process.env.PORT || 8080;
+let app = express();
 
 app.use(express.static(path.join(__dirname, 'public')));
 
-app.get('/', function(request, response) {
-  response.sendFile(__dirname + '/public/index.html');
+app.get('*', function(request, response) {
+  response.sendFile(path.resolve(__dirname, 'public', 'index.html'))
```
Comment (lucyfox4131) [inline server.js]: What's the reasoning here?

Comment (saylerb) [inline server.js]: The splat on line 8 is the main thing that solves the problem of routing.  The change on line  9 is more stylistic. I took these ideas from the react-router tutorial. https://github.com/reactjs/react-router-tutorial/tree/master/lessons/11-productionish-server

File: server.js (hunk 1 above)
Comment (saylerb) [inline server.js]: To be consistent I went with lowercase. I think all caps is reserved for global variables, which I could go with here I guess? Do you run across any stylistic guidelines for that?

File: server.js (hunk 2 above)
Comment (notmarkmiranda) [inline server.js]: @saylerb @lucyfox4131 i think it has to do with taking all requests that come in to establish a history, vs. being the route that is looking to route get '/' to index

File: lib/index.js [hunk 3]
```diff
@@ -1,13 +1,13 @@
 import React from 'react';
 import ReactDOM from 'react-dom';
 import { Navbar, FormGroup, FormControl, Button } from 'react-bootstrap';
-import { Router, Route, browserHistory, hashHistory } from 'react-router';
+import { Router, Route, browserHistory } from 'react-router';
```
Comment (seeker105) [inline lib/index.js]: Why remove the hashHistory/replace with browserHistory?

File: server.js (hunk 2 above)
Comment (AnnaCW) [inline server.js]: Thanks for posting this PR @saylerb. The splat notation used this way is new to me.

Comment (marcellawigg) [inline server.js]: This notation was new to me as well. I am thinking this may resolve an issue I am currently experiencing with my routing.

File: lib/index.js (hunk 3 above)
Comment (Salvi6God) [inline lib/index.js]: @seeker105 

browserHistory is more common to use for server-side rendering in React because it uses the History API built in the browser to give cleaner URLs compared to when using hashHistory. 

You can read more about it in the link below. ⬇️ 

source: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md

On a side-note, there's a slight chance you might use the LookingForMe website to find jobs after you graduate from Turing :)

File: server.js (hunk 2 above)
Comment (saylerb) [inline server.js]: The key is that the express routing should server the React app index.html no matter what the url is. I think external links don't seem to match the the "/" so I need to change it to splat in order to make sure it still serves the app up.  

After express server  serves up the React App, the react router takes over.

File: server.js (hunk 1 above)
Comment (lucyfox4131) [inline server.js]: No guidelines I read. Just wondered why it was changed. Thanks!

**Comment by saylerb** [comment]
I've pushed this up to a staging heroku application here https://afternoon-plains-39747.herokuapp.com/ , and it seems to be working smoothly. I had to remove a `let` variable declaration, since Heroku complained. The changes are now production-ready.

**Comment by robbiejaeger** [comment]
I loaded the staging app and could not reproduce the bug - so it looks good to me.
